name: Build and Push Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: 37 13 * * 0
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Add permissions to ensure GITHUB_TOKEN has write access to packages
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        dockerfile:
          - name: alpine
            file: alpine.Dockerfile
          - name: arch
            file: arch.Dockerfile
          - name: kali
            file: kali.Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        continue-on-error: true
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile.file }}
          platforms: linux/amd64,linux/arm64

          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.dockerfile.name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.dockerfile.name }}-${{ github.sha }}
